In [33]:
# Standard libraries
import os
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from plotnine import *
from IPython.display import display

# Machine Learning
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from scipy.cluster import hierarchy as hc
from fastai.imports import *

In [34]:
#data = pd.read_csv('etc/data/lownoise/coc1000.csv')
#data = pd.read_csv('etc/data/highnoise/coc1000.csv')
#data = pd.read_csv('etc/data/lownoise/coc10000.csv')
data = pd.read_csv('etc/data/highnoise/coc10000.csv')
data.shape

(10000, 25)

In [35]:
data.iloc[5,:]

Loc+         1741
 Acap           4
 Aexp           4
 Arch           1
 Cplx           5
 Data           ?
 Docu           3
 Flex           6
 Ltex           4
 Pcap           1
 Pcon           2
 Plex           2
 Pmat           2
 Prec           3
 Pvol           2
 Rely           1
 Ruse           5
 Sced           2
 Site           1
 Stor           3
 Team           6
 Time           4
 Tool           5
 Risk-          6
 Effort-    42191
Name: 5, dtype: object

In [36]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, random_state=0)

In [37]:
data.replace('?', np.nan, inplace=True)
datanp = data.to_numpy()
datanp[5]

array([1741, '4', '4', '1', '5', nan, '3', '6', '4', '1', '2', '2', '2',
       '3', '2', '1', '5', '2', '1', '3', '6', '4', '5', 6, 42191],
      dtype=object)

In [38]:
dataimp = imp.fit_transform(datanp)
dataimp[5]

array([1.74100000e+03, 4.00000000e+00, 4.00000000e+00, 1.00000000e+00,
       5.00000000e+00, 3.49905519e+00, 3.00000000e+00, 6.00000000e+00,
       4.00000000e+00, 1.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 3.00000000e+00, 2.00000000e+00, 1.00000000e+00,
       5.00000000e+00, 2.00000000e+00, 1.00000000e+00, 3.00000000e+00,
       6.00000000e+00, 4.00000000e+00, 5.00000000e+00, 6.00000000e+00,
       4.21910000e+04])

In [39]:
dataimp[:,:] = np.round(dataimp[:,:])
dataimp[5]

array([1.7410e+03, 4.0000e+00, 4.0000e+00, 1.0000e+00, 5.0000e+00,
       3.0000e+00, 3.0000e+00, 6.0000e+00, 4.0000e+00, 1.0000e+00,
       2.0000e+00, 2.0000e+00, 2.0000e+00, 3.0000e+00, 2.0000e+00,
       1.0000e+00, 5.0000e+00, 2.0000e+00, 1.0000e+00, 3.0000e+00,
       6.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+00, 4.2191e+04])

In [40]:
dfnew = pd.DataFrame(dataimp, columns=data.columns)
#dfnew.to_csv("iter_low_coc1000.csv", index=False)
#dfnew.to_csv("iter_high_coc1000.csv", index=False)
#dfnew.to_csv("iter_low_coc10000.csv", index=False)
dfnew.to_csv("iter_high_coc10000.csv", index=False)